- name: Install system void repos
  xbps:
    name:
      - void-repo-multilib # Void Linux drop-in file for the multilib repository
      - void-repo-multilib-nonfree # Void Linux drop-in file for the multilib/nonfree repository
      - void-repo-nonfree # Void Linux drop-in file for the nonfree repository
    state: present
  become: true

- name: Install system void packages
  xbps:
    name:
      - git # Fast Version Control System
      - git-lfs # Git extension for versioning large files
      - syncthing # Continuous File Synchronization
      - flatpak # Application deployment framework for desktop apps
      - wireguard # Fast, modern, secure vpn tunnel
      - wireguard-tools # Tool for wireguard
      - cronie # Runs specified programs at scheduled times
      - pipewire # Server and user space API to deal with multimedia pipelines
      - libspa-bluetooth # Server and user space API to deal with multimedia pipelines - bluetooth plugins
      - cifs-utils # CIFS filesystem user-space tools
      - ansible # Simple deployment, configuration management and execution framework
      - btrbk # Backup tool for btrfs subvolumes
      - chezmoi # Manage your dotfiles across multiple machines, securely
      - elogind # Standalone logind fork
      - rsync # Remote fast incremental file transfer tool
      - unzip # List, test and extract compressed files in a ZIP archive
      - mimeo # Open files by MIME-type or file name using regular expressions
      - busybox # Swiss Army Knife of Embedded Linux
      - qemu # Open Source Processor Emulator
      - libvirt # Virtualization API for controlling virtualization engines
      - virt-manager # User interface for managing virtual machines
      - bridge-utils # Layer2 ethernet bridging for Linux
      - trash-cli # Command line interface to the freedesktop.org trashcan
      - udiskie # Removable disk automounter using udisks
      - curl # Client that groks URLs
      - wget # GNU wget download utility
      - NetworkManager # Network Management daemon
      - network-manager-applet # NetworkManager panel applet for GNOME
    state: present
  become: true

- name: Add the flathub flatpak repository remote
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: true
