- name: Install terminal dnf packages
  xbps:
    name:
      - neovim # Vim-fork focused on extensibility and agility
      - task # Command-line TODO list manager
      - timewarrior # Timewarrior tracks and reports time
      - vifm # Ncurses-based file manager with vi-like keybindings
      - zsh # Z SHell
      - tmux # Terminal Multiplexer
      - nmap # Utility for network discovery and security auditing
      - w3m  # Text-based Web browser and pager (with Debian patches)
      - lf # Terminal file manager
      - khal # Command-line calendar build around CalDAV
      - khard # Command-line addressbook built around CardDAV
      - vdirsyncer # Synchronize calendars and addressbooks
    state: present
  become: true

- name: Install terminal xbps-src packages 
  tags: ["src"]
  include_tasks: ../include/xbps-src.yml
  loop:
    - package: rbw # Unofficial command line client for bitwarden
      repository: hostdir/binpkgs
