- name: Set desktop files to hide
  include_tasks: _hide-desktop.yml
  loop:
    - /usr/share/applications/wine-winhelp.desktop
    - /usr/share/applications/wine-mime-msi.desktop
    - /usr/share/applications/wine-notepad.desktop
    - /usr/share/applications/wine-oleview.desktop
    - /usr/share/applications/wine-regedit.desktop
    - /usr/share/applications/wine-uninstaller.desktop
    - /usr/share/applications/wine-wineboot.desktop
    - /usr/share/applications/wine-winecfg.desktop
    - /usr/share/applications/wine-winefile.desktop
    - /usr/share/applications/wine-winemine.desktop
    - /usr/share/applications/wine-wordpad.desktop
    - /usr/share/applications/vifm.desktop
    - /usr/share/applications/dosbox-staging.desktop
    - /usr/share/applications/nvim.desktop
    - /usr/share/applications/syncthing-start.desktop
    - /usr/share/applications/syncthing-ui.desktop
