- name: Clone or pull void-packages 
  ansible.builtin.git:
    repo: 'https://github.com/void-linux/void-packages.git'
    dest: /home/{{ user }}/git/void-packages 
    update: yes
  register: git_return

- name: Bootstrap if newly cloned 
  ansible.builtin.command: ./xbps-src binary-bootstrap
  args:
    chdir: /home/{{ user }}/git/void-packages
  when: not git_return.before
    
- name: Enable restricted if newly cloned
  copy:
    dest: /home/{{ user }}/git/void-packages/etc/conf
    content: |
      XBPS_ALLOW_RESTRICTED=yes
  when: not git_return.before

- name: Package {{ item.package }} with xbps-src
  ansible.builtin.command: ./xbps-src pkg {{ item.package }}
  args:
    chdir: /home/{{ user }}/git/void-packages

- name: Install packaged {{ item.package }}
  expect:
    command: xbps-install --repository {{ item.repository }} {{ item.package }}
    responses:
      continue: y 
  args:
    chdir: /home/{{ user }}/git/void-packages
  become: true
