import = []

[[session]]
name = "edit-dots"
path = "~/.local/share/chezmoi"
startup_command = "~/.config/sesh/scripts/two_window_editor"

[[session]]
name = "edit-vortex"
path = "~/Documents/devel/kube/fluxcd"
startup_command = "~/.config/sesh/scripts/vortex_editor"
